// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/livana-hero/FullBleed.tsx": () => import("../components/mockups/livana-hero/FullBleed.tsx"),
  "./components/mockups/livana-hero/Magazine.tsx": () => import("../components/mockups/livana-hero/Magazine.tsx"),
  "./components/mockups/livana-hero/SplitScreen.tsx": () => import("../components/mockups/livana-hero/SplitScreen.tsx")
};
